// <auto-generated from .class.json>
// Namespace: MyApp.Models
import { Address } from './address';
export class JobOffer {
  title: string = '';
  startDate: Date | null = null;
  salary: number = 0;
  tags: string[] = [];
  address: Address = new Address();

  constructor(init?: Partial<JobOffer>) {
    Object.assign(this, init);
    if (typeof this.startDate === 'string') this.startDate = new Date(this.startDate as unknown as string);
  }
}
