// <auto-generated from .class.json>
// Namespace: MyApp.Models
import { Address } from './address';
import { Title } from './title';
import { Job } from './job';
export class Person {
  id: number = 0;
  name: string = '';
  email: string | null = null;
  tags: string[] = [];
  address: Address = new Address();
  title: Title = new Title();
  jobs: Job[] = [];

  constructor(init?: Partial<Person>) {
    Object.assign(this, init);
  }
}
