// <auto-generated from .class.json>
// Namespace: MyApp.Models
export class Title {
  course: string = '';
  yearOfCompletion: number = 0;

  constructor(init?: Partial<Title>) {
    Object.assign(this, init);
  }
}
