// <auto-generated from .class.json>
// Namespace: MyApp.Models
export class Address {
  streetName: string = '';
  number: string = '';
  district: string = '';
  city: string = '';
  country: string = '';

  constructor(init?: Partial<Address>) {
    Object.assign(this, init);
  }
}
