// <auto-generated from .class.json>
// Namespace: MyApp.Models
export class Job {
  title: string = '';
  startDate: Date | null = null;
  endDate: Date | null = null;

  constructor(init?: Partial<Job>) {
    Object.assign(this, init);
    if (typeof this.startDate === 'string') this.startDate = new Date(this.startDate as unknown as string);
    if (typeof this.endDate === 'string') this.endDate = new Date(this.endDate as unknown as string);
  }
}
